version: "3.7"

services:
  backend:
    image: backend
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: ts-node-docker
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: yarn start
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5438:5438'
    environment:
      - DB_USER=postgres
      - DB_NAME=node_postgres
      - DB_PASSWORD=1111
      - DB_HOST=localhost
      - DB_PORT=5438
      - POSTGRES_HOST_AUTH_METHOD=trust
      - NODE_APP_PORT=8080