version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    container_name: ts-node-docker
    expose:
      - '8080'
    ports:
      - '8080:8080'
    command: yarn start